### ISSUE TITLE
Micronaut HOL Lab discrepancies

### ISSUE THREAD

**Issue by danielkec** [oracle/learning-library#1824]
FYI @ljamen @graemerocher @recursivecodes @paulparkinson @Verdent @tomas-langer 

- [x] **Lab 2 Step 3.2** --- In lab 3 the script prompts you for the public ip but it is not listed as one of the options you need to note in lab 2. - PR #1825 

- [x] extra `bash` word in the copy-able snippets - PR #1830

- [x] **Lab 2 Step 2.1** -- missing telling the user to click Plan on the Plan Info dialog (this is what kicks off the report) - PR #1831

- [x] **Lab 4 Step 2** Unlike for domain objects, there is no directory advised for repositories to be created in - PR #1832

- [x] **Lab 4, Step 4** Unused imports in `Application.java` snippet - PR #1833

- [x] **Lab 5, Step 1** Download and run should be more specific(execution rights) - PR #1834

- [x] **Lab 5, Step 1** Wrong port in Helidon health curl - PR #1835

- [x] **Lab3, Step 1.3** Snippet generated by `setup.sh` should be scping `./build/libs/example-atp-0.1-all.jar` and not `build/libs/micronaut-data-jdbc-graal-atp-0.1-all.jar`

- [x] **Lab 6** Scp is using `~/.ssh/id_oci` but we have created `id_rsa` in the **Lab 1**

- [x] **Lab 2, Step 1.6** `cat ~/.ssh/id_oci.pub | pbcopy - pbcopy` seems to be OSX specific
- [x] **Lab 3, Step 2.2** "Make sure you are in the `mn-oci-hol` compartment"
but ..
compartment name is mentioned only in Lab 2, Step 1.5 and differently
![image](https://user-images.githubusercontent.com/1773630/91758749-ca6baa80-ebd0-11ea-86ee-b21767fe7651.png)
- [x] **Lab 3, Step 1.2**
```bash
Step 6: Run your JAR on the VM with:
./setup.sh: line 64: unexpected EOF while looking for matching `"'
./setup.sh: line 68: syntax error: unexpected end of file
```
There is extra quote on the end of the line 62
```bash
echo "java -jar -DMICRONAUT_OCI_DEMO_PASSWORD=${DB_USER_PASSWORD} /app/application.jar""
```

- [ ] **Lab 6 -Lab 7** Deploy and run step is followed by Terminate and Destroy OCI resources, there is no "curling" with running app
- [ ] The prerequisites and Lab 1 seem to be the same. Is that intentional or could we just start with Intro and then Lab 1 (skip the prereq)

- [ ] A prereq to **lab 2** is having the ssh key that you created in lab 1. The text in **Lab 2 Step 1.6** states that the ssh key was generated in **Lab 2** (should be **Lab 1**).

- [ ] **Lab 2 Step 3.2** > the explanation at the end of the step re: how to get these values again in the next lab is a bit confusing. Maybe just a screenshot showing the options to select would work better (also should probably put this in the next lab when they actually need to do it)

- [ ] **Lab 2, Step 2.4** Sub-compartment `mn-oci-hol` is created under different compartment then selected
![image](https://user-images.githubusercontent.com/1773630/91759888-b32dbc80-ebd2-11ea-824d-22977e63b4f9.png)
![image](https://user-images.githubusercontent.com/1773630/91759898-b759da00-ebd2-11ea-8946-3ef5cb551147.png)

- [ ] **Lab 2, STEP 3.1** In the Micronaut section, it doesn't appear that the passwords have been obscured. While I doubt this really matters since we don't know what instance, nor credentials are being used -- I would recommend some redacting be applied. or example, this image: https://github.com/oracle/learning-library/blob/master/developer-library/micronaut-oci-atp/provision/images/tf_output.png

- [ ] **In Introduction.md**, Section heading "About Micronaut" change to "About Micronaut and Helidon," Shouldn't Helidon be listed as a prerequisite?

**Comment by graemerocher** [comment]
@recursivecodes Can you look at the `setup.sh` script and the error that is occurring when running it:

```
Step 6: Run your JAR on the VM with:
./setup.sh: line 64: unexpected EOF while looking for matching `"'
./setup.sh: line 68: syntax error: unexpected end of file
```

**Comment by recursivecodes** [comment]
The following issues have been addressed:

> Lab 6 Scp is using ~/.ssh/id_oci but we have created id_rsa in the Lab 1
> Lab3, Step 1.3 Snippet generated by setup.sh should be scping ./build/libs/example-atp-0.1-all.jar and not build/libs/micronaut-data-jdbc-graal-atp-0.1-all.jar
> Lab 3, Step 1.2 ./setup.sh: line 64: unexpected EOF while looking for matching `"'
> Lab 3, Step 2.2 "Make sure you are in the mn-oci-hol compartment" but ..compartment name is mentioned only in Lab 2, Step 1.5 and differently

> Lab 2, Step 1.6 cat ~/.ssh/id_oci.pub | pbcopy - pbcopy seems to be OSX specific

The lab specifically mentions OSX in regard to the following issue, so no update is needed. Users on other OS can copy/paste manually.

> Lab 2 Step 3.2 > the explanation at the end of the step re: how to get these values again in the next lab is a bit confusing. Maybe just a screenshot showing the options to select would work better (also should probably put this in the next lab when they actually need to do it)

I disagree with this feedback - it's quite clear to me. If someone else would like to clarify via a PR please do so.

> Lab 2, STEP 3.1 In the Micronaut section, it doesn't appear that the passwords have been obscured

This instance is long gone - no need to worry about the passwords being obscured.

The latest `setup.sh` is available in Object Storage.

**Comment by danielkec** [comment]
@recursivecodes great script output now looks much nicer
There is small regression in the `setup.sh` on line 71:
```
echo "export MICRONAUT_OCI_DEMO_PASSWORD=${DB_USER_PASSWORD}"
```
`MICRONAUT_OCI_DEMO_PASSWORD` should be wallet password, not schema password. Schema password should be in `DATASOURCES_DEFAULT_PASSWORD` variable. 

```bash
echo "export DATASOURCES_DEFAULT_PASSWORD=${DB_USER_PASSWORD}"
echo "export MICRONAUT_OCI_DEMO_PASSWORD=${WALLET_PASSWORD}"
echo "export TNS_ADMIN=/tmp/wallet"
echo "java -jar /app/application.jar"
```

**Comment by recursivecodes** [comment]
https://github.com/oracle/learning-library/pull/1845

Also, setup script updated in object storage.

**Comment by nagypeter** [comment]
- Lab 3 _Setup Your Environment_ contains the new Micronaut application creation. Why it is not part of Lab 4 _Build a Micronaut Application_ itself?
- Lab 3 DB setup script prints: Run java application. But the application doesn't exist at that point. Can be confusing.
- Lab 3/Step 2/7: wallet saving location can be different. E.g. Windows machine doesn't have `/tmp`
- Lab 3 I would be more clear about how to create/initiate the Micronaut project. Stick to one proven option e.g. download the project as zip and recommend other like Micronaut CLI (if he/she has already) or use Micronaut Launch web page.
- Lab 5/Step 1: `curl` would be more platform independent instead of `wget`. However git clone+mvn build is more obvious, platform independent and doesn't require explanation. Especially workshop doesn't focus on startup time and native executable. 
- Lab 5/Step 1: short explanation about what is health, metrics, openapi endpoints. Also Helidon code sample would be worth to include. Demonstrate simplicity, Microprofile, etc. 
- Lab 6/Step 1/1: wallet location can be different than `/tmp/wallet` on desktop. Would be useful a reminder.
- Lab 6/Step 1/3: on the VM there is no `/app` folder to copy application.jar there thus gives error. Home directory?
- Lab 6/Step 1/4: if you git clone+build Helidon app then you don't have helidon-mp-service native executable binary on your desktop. On the other hand (helidon native binary) download script can work directly on VM. Need `ssh` to the instance. 
- Lab 6/Step 1/5,6: include copiable `ssh` command if `scp` is provided. Would be more clear where and how to run the applications.

**Comment by graemerocher** [comment]
@nagypeter thanks for the feedback we will address some of these points

**Comment by graemerocher** [comment]
@nagypeter I have sent a PR to address much of the feedback. Regarding the Helidon changes, it may be best if @tomas-langer takes a look at those

**Comment by graemerocher** [comment]
This can be closed. I believe we have addressed all the feedback we could
